### ISSUE TITLE
MNNKit流程问题

### ISSUE THREAD

**Issue by ToBigboss** [alibaba/MNNKit#12]
这个流程是隔几帧才检测一次的把？  有更好的跟踪方案么

**Comment by suancaiyu** [comment]
> 这个流程是隔几帧才检测一次的把？ 有更好的跟踪方案么

视频场景下是隔帧检测的，但是每一帧都会重新定位关键点位置，目前这是一种性能比较好的方式

**Comment by flyingmrwang** [comment]
@suancaiyu 隔帧检测（比如20帧检测一帧），会不会导致检测的roi与关键点跟踪的roi存在偏差呢？如果有偏差的话，是不是检测的那一帧关键点也会相应抖动一下？
