### ISSUE TITLE
MNNFaceDetection.framework和MNNKitCore.framework,MNN.framework能否提供静态库的版本呢？

### ISSUE THREAD

**Issue by guihuaYi** [alibaba/MNNKit#13]
因为一些原因，我想使用静态库的方式使用，研发哥哥能否支持呢。

**Comment by oopming** [comment]
同问，是否提供静态库版本

**Comment by suancaiyu** [comment]
> 同问，是否提供静态库版本

可以的，请问你们什么场景下一定要使用静态库呢

**Comment by oopming** [comment]
我们团队内部规范建议三方库是用静态库的，引入其他三方库也都是用静态库

**Comment by guihuaYi** [comment]
动态库集成到其他app会报错，安装真机运行不起来，我用的是xcode自动管理签名。但是你们提供的MNNKit的demo是可以运行的。

**Comment by oopming** [comment]
> > 同问，是否提供静态库版本
> 
> 可以的，请问你们什么场景下一定要使用静态库呢

我们团队内部规范建议三方库是用静态库的，引入其他三方库也都是用静态库

**Comment by suancaiyu** [comment]
> > > 同问，是否提供静态库版本
> > 
> > 
> > 可以的，请问你们什么场景下一定要使用静态库呢
> 
> 我们团队内部规范建议三方库是用静态库的，引入其他三方库也都是用静态库

iOS静态库的版本已经发布，文档中有更新，repo更新下
