### ISSUE TITLE
iOS真机安装不成功，报错信息如下

### ISSUE THREAD

**Issue by guihuaYi** [alibaba/MNNKit#14]
直接把三个动态framework拖到demo工程，都跑不起来，错误信息，请看附件图片。有人遇到过么？
<img width="512" alt="111" src="https://user-images.githubusercontent.com/16831775/77133988-1e118e00-6aa0-11ea-9dd1-44d52c03e2d2.png">

**Comment by guihuaYi** [comment]
补充一下，不引入sdk三个库的时候，app是能正常跑起来，加入进去就不行了。

**Comment by suancaiyu** [comment]
> 直接把三个动态framework拖到demo工程，都跑不起来，错误信息，请看附件图片。有人遇到过么？
> <img alt="111" width="512" src="https://user-images.githubusercontent.com/16831775/77133988-1e118e00-6aa0-11ea-9dd1-44d52c03e2d2.png">

从设备中删除应用，然后重新run

**Comment by guihuaYi** [comment]
按照你说的做了，还是不行，我怀疑三个framework是不是被签名过，我查了一下stackoverflow，里面的回答是说要重新编译三个库。
https://stackoverflow.com/questions/34642165/this-applications-bundle-identifier-does-not-match-its-code-signing-identifier

**Comment by suancaiyu** [comment]
> 按照你说的做了，还是不行，我怀疑三个framework是不是被签名过，我查了一下stackoverflow，里面的回答是说要重新编译三个库。
> https://stackoverflow.com/questions/34642165/this-applications-bundle-identifier-does-not-match-its-code-signing-identifier

因为这几个都是打的动态库，系统在加载动态库的时候会检查framework的签名，签名中的TeamIdentifier和你应用的TeamIdentifier必须一致，而我打的库其实是没有TeamIdentifier的，所以你要么只能在模拟器运行，真机签名永远对不上的。
解决方法：
1. 工程用cocoaPods依赖
2. 这周我会发布一个静态库的版本，就不会有这个问题了

**Comment by guihuaYi** [comment]
谢谢解答，第一种方案是可行的，期待给一个静态库版本，我想直接使用静态库的形式，不太想用cocoaPods管理。

**Comment by suancaiyu** [comment]
> 谢谢解答，第一种方案是可行的，期待给一个静态库版本，我想直接使用静态库的形式，不太想用cocoaPods管理。

其实cocoaPods也是通过重签名使用动态库的，如果你在应用中对framework重签名也能解决这个问题。静态库的版本刚刚已经发布了，更新下repo
