### ISSUE TITLE
Landmark model 预处理方式？

### ISSUE THREAD

**Issue by xuguozhi** [alibaba/MNNKit#16]
请问关键点的模型的输入是什么形式的？image_size多大？RGB or gray？mean_vals, norm_vals,请指教一下

**Comment by suancaiyu** [comment]
MNNKit目前只开放应用层能力，算法和模型暂时还不开放

**Comment by hsl20130659** [comment]
你知道了也没用，还有后处理，我知道图像输入大小是112*112
