### ISSUE TITLE
 'MNN' uses the unencrypted 'http' protocol to transfer the Pod.

### ISSUE THREAD

**Issue by fatly** [alibaba/MNNKit#17]
Update all pods
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing FMDB (2.7.5)
Installing MNN (0.2.2.2)

[!] Error installing MNN
[!] /usr/bin/curl -f -L -o /var/folders/t4/zsm4n0kd5rs25cfpkfjw60lm0000gn/T/d20200331-38860-1dqjspc/file.zip http://mnnkit.oss-cn-hangzhou.aliyuncs.com/pods-repo/MNN/0.2.2.2/MNN.framework.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to 127.0.0.1 port 1080: Connection refused

[!] 'MNN' uses the unencrypted 'http' protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts. Otherwise, please reach out to the library author to notify them of this security issue.

**Comment by suancaiyu** [comment]
> Failed to connect to 127.0.0.1 port 1080: Connection refused
这个是warning不影响下载，检查下你是不是开了代理，或者端口是不是被占用了
