### ISSUE TITLE
我用图片模式检测的时候，传入自己拍的照片，识别不出来，接口返回nil，error也是空，用demo的图片能识别出来。能帮忙查一下啥原因么？

### ISSUE THREAD

**Issue by guihuaYi** [alibaba/MNNKit#21]
![test](https://user-images.githubusercontent.com/16831775/79210015-cab01700-7e76-11ea-9760-8d856b0bbd28.JPG)
这个是我的图片。

接口调用：

 NSArray<MNNFaceDetectionReport *> *reports = [self.faceDetector inferenceWithImage:self.image config:0 angle:0 outAngle:0 flipType:FLIP_NONE error:&error];

reports为空，error也是nil。

**Comment by suancaiyu** [comment]
> ![test](https://user-images.githubusercontent.com/16831775/79210015-cab01700-7e76-11ea-9760-8d856b0bbd28.JPG)
> 这个是我的图片。
> 
> 接口调用：
> 
> NSArray<MNNFaceDetectionReport *> *reports = [self.faceDetector inferenceWithImage:self.image config:0 angle:0 outAngle:0 flipType:FLIP_NONE error:&error];
> 
> reports为空，error也是nil。

你这张图片不是正向的，可以把它旋转到正向，或者设置输入角度inAngle为90度；另外注意初始化的时候要配置检测模式为图片模式

**Comment by GucciPrada** [comment]
多谢多谢，的确是这个问题

**Comment by guihuaYi** [comment]
多谢多谢，的确是角度需要旋转到正向
