### ISSUE TITLE
Swift Setup

### ISSUE THREAD

**Issue by Phando** [alibaba/MNNKit#22]
Hello,
I was seeing good results with this library in ObjectiveC, but I was required to integrate it into a Swift app. Below are my findings. 

First the podfile
```
platform :ios, '13.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'MyProject' do
  # Pods for MyProject
  pod 'MNNFaceDetection'
  pod 'MNNHandGestureDetection'
  pod 'MNNPortraitSegmentation'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
```

Then in your target application you need to mark ENABLE_BITCODE to No

Enjoy

**Comment by suancaiyu** [comment]
> Hello,
> I was seeing good results with this library in ObjectiveC, but I was required to integrate it into a Swift app. Below are my findings.
> 
> First the podfile
> 
> ```
> platform :ios, '13.0'
> source 'https://github.com/CocoaPods/Specs.git'
> 
> target 'MyProject' do
>   # Pods for MyProject
>   pod 'MNNFaceDetection'
>   pod 'MNNHandGestureDetection'
>   pod 'MNNPortraitSegmentation'
> end
> 
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     target.build_configurations.each do |config|
>       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
>     end
>   end
> end
> ```
> 
> Then in your target application you need to mark ENABLE_BITCODE to No
> 
> Enjoy

sorry，we hasn't support bitcode yet. Your project may disable the bitcode
