### ISSUE TITLE
什么情况下，函数inferenceWithPixelBuffer...返回nil？

### ISSUE THREAD

**Issue by doctorimage** [alibaba/MNNKit#23]
- (NSArray<MNNFaceDetectionReport *> *)inferenceWithPixelBuffer:(CVPixelBufferRef)pixelBuffer config:(MNNFaceDetectConfig)detectConfig
                                                          angle:(float)inAngle outAngle:(float)outAngle flipType:(MNNFlipType)flipType
                                                          error:(NSError *__autoreleasing *)error;
这个函数，1）没有buffer，结果为nil；2）若buffer不空，且是没有人脸的正常视频，那也是有可能返回nil的，那么这种buffer不空情况下，推理结果为nil，是什么情况？还是哪里设置不对？3）有无第三种情况，返回结果为nil？

**Comment by suancaiyu** [comment]
> * (NSArray<MNNFaceDetectionReport *> *)inferenceWithPixelBuffer:(CVPixelBufferRef)pixelBuffer config:(MNNFaceDetectConfig)detectConfig
>   angle:(float)inAngle outAngle:(float)outAngle flipType:(MNNFlipType)flipType
>   error:(NSError *__autoreleasing *)error;
>   这个函数，1）没有buffer，结果为nil；2）若buffer不空，且是没有人脸的正常视频，那也是有可能返回nil的，那么这种buffer不空情况下，推理结果为nil，是什么情况？还是哪里设置不对？3）有无第三种情况，返回结果为nil？

输入的数据里面没有人脸，或者人脸的方向不对，都会造成检测结果空。可以参照demo修改
