### ISSUE TITLE
106关键点如何实现旋转View后，还可以吻合呢？

### ISSUE THREAD

**Issue by ETmanwenhan** [alibaba/MNNKit#25]
CGAffineTransform t = CGAffineTransformRotate(CGAffineTransformIdentity, M_PI_4);
self.detectView.transform = t;

106关键点就对不上了。要求先设置transform，然后绘制关键点。急，求解答，谢谢！

**Comment by suancaiyu** [comment]
> CGAffineTransform t = CGAffineTransformRotate(CGAffineTransformIdentity, M_PI_4);
> self.detectView.transform = t;
> 
> 106关键点就对不上了。要求先设置transform，然后绘制关键点。急，求解答，谢谢！

这个其实很简单，你把view旋转了，那对应的点位也角度变换下
