### ISSUE TITLE
mnnkit是否可以免费商用

### ISSUE THREAD

**Issue by xiaxiaoyu222** [alibaba/MNNKit#32]

**Comment by suancaiyu** [comment]
禁止以MNNKit SDK为基础，封装任何商业或盈利目的的三方SDK
允许在非商业或盈利目的前提下，基于MNNKit SDK开发上层SDK，但必须使用MNN Kit License发布
允许有商业或盈利目的的应用集成MNNKit，应用中某项收费能力可能是基于MNNKit SDK开发的
https://raw.githubusercontent.com/alibaba/MNNKit/master/license 可以看下我们的开放协议

**Comment by huzhen1025** [comment]
关于MNNKit License的解析
2.2	Unless otherwise provided in this Agreement, you have no right to sub-license or redistribute the “SDK” or “MNN Kit” to any third party.
2.2 除非本协议另有规定，您无权将“SDK”或“MNN Kit”再许可或重新分发给任何第三方。
问题是：集成在端侧，用户的手机安装，是属于重新分发给第三方了吗？如果算是分发给第三方了，那么在这个协议下，如何商用呢？
