### ISSUE TITLE
编译运行不过去吧

### ISSUE THREAD

**Issue by wengfei** [alibaba/MNNKit#4]
对应的kit包，so库 会开源吗

**Comment by suancaiyu** [comment]
MNNKit SDK只开放能力不开源，使用协议可以阅读下[licence](https://github.com/alibaba/MNNKitDemo/blob/master/license)。
请问哪个工程编译不过去呢，安卓还是iOS，有日志吗？

**Comment by wengfei** [comment]
android:
![abc](https://user-images.githubusercontent.com/1897760/74028728-085f7200-49e6-11ea-96f2-938187c4cda7.png)
另外，会开房用于人脸识别的 face embedding 的能力吗， 特征码，我用 insightface 的模型还是太大了。

**Comment by LucaChen** [comment]
编译不过去，和楼上一样的错误

**Comment by wengfei** [comment]
基础 jar 或者 aar 没有放出来

**Comment by yangxiaoen** [comment]
> 基础 jar 或者 aar 没有放出来

请问楼上是怎么解决的

**Comment by yangxiaoen** [comment]
> 编译不过去，和楼上一样的错误

请问 问题解决了吗

**Comment by wengfei** [comment]
如果你想测试的话，可以解开 他那个 测试 app，里面有 缺少的 class。

**Comment by suancaiyu** [comment]
> > 编译不过去，和楼上一样的错误
> 
> 请问 问题解决了吗

更新了版本，重新拉下来看看

**Comment by wengfei** [comment]
不行
