### ISSUE TITLE
IOS issue

### ISSUE THREAD

**Issue by xuguozhi** [alibaba/MNNKit#6]
Hi，after I open MNNKitDemo.xcworkspace, an error occurred:

`
Showing All Messages
No account for team "2QB4NHW4W2". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.
`

**Comment by suancaiyu** [comment]
> Hi，after I open MNNKitDemo.xcworkspace, an error occurred:
> 
> `Showing All Messages No account for team "2QB4NHW4W2". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.`

In the target preferences, enable "Automatic manage signing" then assign the target to your team.
