### ISSUE TITLE
请教关于人脸关键点遮挡分类的训练思路

### ISSUE THREAD

**Issue by lyycfairy** [alibaba/MNNKit#7]
你好，我知道模型和相关代码是不开源的
但是关于人脸关键点是否遮挡的这个分类，一直有疑问，很想请教一下

因为遮挡物可能是任意形状任意物体，很难通过在训练集中添加遮挡物并标注来训练成一个泛化性很好的模型，是否有其他更好的思路呢

新入门菜鸟一名，还望各位大牛指点，万分感谢！

**Comment by xuguozhi** [comment]
你好，请问关键点遮挡的判别是否有相关文献参考？十分感谢！

**Comment by jink12** [comment]
> 你好，我知道模型和相关代码是不开源的
> 但是关于人脸关键点是否遮挡的这个分类，一直有疑问，很想请教一下
> 
> 因为遮挡物可能是任意形状任意物体，很难通过在训练集中添加遮挡物并标注来训练成一个泛化性很好的模型，是否有其他更好的思路呢
> 
> 新入门菜鸟一名，还望各位大牛指点，万分感谢！

目前遮挡主要只针对常见的情况，如果需要泛化性好主要还是通过增加遮挡的数据类型，同时分割的思想也可以借鉴

**Comment by suancaiyu** [comment]
> 你好，请问关键点遮挡的判别是否有相关文献参考？十分感谢！

Lv J, Shao X, Xing J, et al. A deep regression architecture with two-stage re-initialization for high performance facial landmark detection[C]//Proceedings of the IEEE conference on computer vision and pattern recognition. 2017: 3317-3326.
